// schools.js
window.schoolData = [
  { district: "萬里區", name: "大坪國小" },
  { district: "汐止區", name: "白雲國小" },
  { district: "汐止區", name: "金龍國小" },
  { district: "蘆洲區", name: "仁愛國小" },
  { district: "蘆洲區", name: "成功國小" },
  { district: "三重區", name: "重陽國小" },
  { district: "三重區", name: "碧華國小" },
  { district: "樹林區", name: "育林國中" },
  { district: "三峽區", name: "介壽國小" },
  // { district: "新店區", name: "莊敬高職" },
  { district: "新店區", name: "北新國小" },
  { district: "石碇區", name: "永定國小" },
  { district: "新店區", name: "新店國小" },
  { district: "板橋區", name: "重慶國中" },
  { district: "板橋區", name: "江翠國中" },
  { district: "板橋區", name: "海山國小" },
  { district: "板橋區", name: "板橋國小" },
  { district: "板橋區", name: "中山國小" },
  { district: "淡水區", name: "新興國小" },
  { district: "八里區", name: "米倉國小" },
  { district: "淡水區", name: "淡水國小" },
  { district: "林口區", name: "崇林國中" },
  { district: "新莊區", name: "新泰國中" },
  { district: "新莊區", name: "中港國小" },
  { district: "泰山區", name: "義學國小" },
  { district: "中和區", name: "錦和高中" },
  { district: "中和區", name: "光復國小" },
  { district: "永和區", name: "秀朗國小" },
];
